name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          npm run build
        env:
          GEMINI_API_KEY: ${{ secrets.VITE_GEMINI_API_KEY }}
          VITE_GEMINI_API_KEY: ${{ secrets.VITE_GEMINI_API_KEY }}
          VITE_FIREBASE_API_KEY: "AIzaSyAPvMZvLIXBHfY-jb6Y-5OA-HmPOgf5Z1E"
          VITE_FIREBASE_AUTH_DOMAIN: "daiei-corexia.firebaseapp.com"
          VITE_FIREBASE_PROJECT_ID: "daiei-corexia"
          VITE_FIREBASE_STORAGE_BUCKET: "daiei-corexia.firebasestorage.app"
          VITE_FIREBASE_MESSAGING_SENDER_ID: "518280505569"
          VITE_FIREBASE_APP_ID: "1:518280505569:web:2ead1c51c6dd66bce6afa0"

      - name: Deploy Firestore Rules to Firebase
        if: ${{ secrets.FIREBASE_TOKEN != '' }}
        run: npx firebase-tools deploy --only firestore:rules --token "${{ secrets.FIREBASE_TOKEN }}"

      - name: Deploy to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages

      - name: Setup Pages
        continue-on-error: true
        uses: actions/configure-pages@v4

      - name: Upload artifact
        continue-on-error: true
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        continue-on-error: true
        id: deployment
        uses: actions/deploy-pages@v4

